module RubyBill
  VERSION: String

  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  attr_accessor self.bearer: String
  attr_accessor self.tenant_id: String

  def config: -> untyped
end
